export { default as Navigation } from "../src/WebpageComponents/Navigation";
export { default as Home } from "../src/WebPages/Home";
export { default as Add_Profile } from "../src/WebPages/Add_Profile";
export { default as Add_Plant } from "../src/WebPages/Add_Plant";
export { default as Analytics } from "../src/WebPages/Analytics";
export { default as Update_Prof } from "../src/WebPages/Update_Prof";
export { default as Remove_Prof } from "../src/WebPages/Remove_Prof";
export { default as Update_Plant } from "../src/WebPages/Update_Plant";
export { default as Remove_Plant } from "../src/WebPages/Remove_Plant";
